config/routes.rb
Rails.application.routes.draw do

  root to: 'topics#index'

  resources :topics do
  	resources :sub_topics do
      member do
        put :upvote
      end

      # collection do
      #   get :search
      # end

    	resources :comments
    end
  end

  resources :comments
  
  resources :sessions do

  end

  
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/signin', to: 'sessions#new', via: :get

end

app/models/Comment.rb
class Comment
  include Mongoid::Document
  include Mongoid::Timestamps

	field :mail , type: String
  field :body , type: String
  field :active , type: Boolean , default: true

  embedded_in :sub_topic

	validates :body, presence: true 

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :signed_in_user, only: [:create]

	def new 
    @topic = Topic.where(active: true).find_by(title: params[:topic_id])
    @subtopic = @topic.sub_topics.where(active: true).find_by(id: params[:id])
    @comment = Comment.new
  end  

  def create
    @topic = Topic.find_by(title: params[:topic_id])
    @subtopic = @topic.sub_topics.where(active: true).find_by(id: params[:id])
    comment = Comment.new(
      :mail => cookies[:mail],
      :body => params[:comment][:body],

      )
    @subtopic.comments << comment
    @subtopic.save
    redirect_to topic_sub_topic_path(:id => @subtopic.id)
  end

  private
    def comment_params
      params.require(:comment).permit(:mail, :body)
    end
    
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.slim
div.comments
  
  h2.comment-headline = @sub_topic.comments.count.to_s + ' Comments' 

  - @sub_topic.comments.each do |comment|   
    ul 
      li.comment-container
        i.icon-large.icon-user
        .comment-section  
          span.created-by 
            = "#{comment.mail.to_s.split('@').first}"
          br  
          span.comment-body
            = comment.body 
          br  
          span.created-at
            = "posted #{distance_of_time_in_words_to_now(comment.created_at).to_s}" + ' ago' 
    
  h2.comment-add Add a comment:

  = form_for Comment.new ,url: topic_sub_topic_comments_path(:sub_topic_id => @sub_topic.id , :id => @sub_topic.id) , html: { method: :post } do |f| 
    div.text
      p = f.label :body 
        = f.text_field :body 
      	= f.submit "Submit", class: "btn btn-info" 
    
	
  