config/routes.rb
Rails.application.routes.draw do

  root to: 'topics#index'

  resources :topics do
  	resources :sub_topics do
      member do
        put :upvote
      end

      # collection do
      #   get :search
      # end

    	resources :comments
    end
  end

  resources :comments
  
  resources :sessions do

  end

  
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/signin', to: 'sessions#new', via: :get

end

app/models/Topic.rb
class Topic
	include Mongoid::Document
  include Mongoid::Timestamps

  field :title , type: String
  field :image_file, type: String, default: "/uploads/default1.png"
  field :image_url, type: String
  field :description, type: String
	field :created_by , type: String
  field :active , type: Boolean , default: true

  embeds_many :sub_topics

  validates :title, presence: true

  def to_param
    title
  end

  def image
    image_url.blank? ? image_file : image_url
  end

  def can_edit?(user)
    self.created_by == user.mail || user.admin?
  end
    
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
	before_filter :signed_in_user, only: [:new, :create, :destroy]
	before_filter :correct_user, only: :destroy

	def index
		@topics = Topic.where(active: true).all
		if @topics == nil
			@topics = []
		end		
	end

	def new
    @title = "Create new Kick"
		@topic = Topic.new
	end

	def create
    # if image is local file
		uploader_image_file = ImageUploader.new
    uploader_image_file.store!(params[:topic][:image_file])

		@topic = Topic.new(
			title: params[:topic][:title],
      description: params[:topic][:description],
      image_file: uploader_image_file.url,
      image_url: params[:topic][:image_url],
			created_by: cookies[:mail],
			)
		if @topic.save
			flash[:success] = "Subject created successfully"
    	redirect_to topics_path
    else
      flash[:error] = "Fields can't be blank"
      redirect_to :back  
    end  	
	end

	def destroy	
    @topic = Topic.find_by(title: params[:id])
		if @topic.can_edit?(current_user)
			@topic.set(active: false)
			flash[:success] = "Kick destroyed."
			redirect_to :back
		else
			flash[:error] = "You cant destroy this Kick."
			redirect_to root_path
		end
	end

	def edit
    @title = "Edit Your Kick"
    @topic = Topic.find_by(title: params[:id])
    if current_user.mail != @topic.created_by && !current_user.admin?
      flash[:notice] ="Sorry, you can't edit this Kick"
      redirect_to :back
    end  
    render :new
  end

  def update
    # if image is local file
  	uploader_image_file = ImageUploader.new
    uploader_image_file.store!(params[:topic][:image_file])

    params[:topic][:image_file] = uploader_image_file.url
    @topic = Topic.find_by(title: params[:id])
    if @topic.update(secure_params)
      flash[:notice] = "Your Kick #{@topic.title} has been updated" 
      redirect_to root_path
    else
      flash[:error] = "Fields can't be blank"
      redirect_to :back    
    end  
  end

	private

    def correct_user
      @topic = Topic.find_by(title: params[:id])
      redirect_to root_url if @topic.nil?
    end

    def secure_params
      params.require(:topic).permit(:title, :image_file, :image_url, :description)
    end
	
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/edit.html.slim
div.row
	div.span6.offset3

		h3 Edit your Kick
		= form_for @topic do |f| 
		  = f.label :title 
		  = f.text_field :title 
		  br
			= f.submit "Update your Kick", class: "btn btn-info" 
			p
				= f.file_field :image 

app/views/topics/index.html.slim
- provide(:title, "Kick-It")
div
  h1 Welcome

div
  = link_to 'Create new Kick' , new_topic_path, class: "btn btn-info" 

div.topic-read
  ul.thumbnails
   - @topics.each do |topic|
    li.span4 
      div.pull-right
        -if current_user && topic.can_edit?(current_user)

          = link_to "Remove ", topic, method: :delete, data: { confirm: "You sure?" }                   
          a.i.icon-large.icon-pencil href = edit_topic_path(id: topic.title)
        .topic-image   
          .topic-title= topic.title 
           
          = link_to image_tag(topic.image) , topic_sub_topics_path(topic_id: topic.title) , class: "thumbnail"

app/views/topics/new.html.slim
div.row
  div.span6.offset3

    h2 = @title

    = form_for @topic do |f| 

      = f.label :title 
      = f.text_field :title 
      p
        = f.label :description, "Description (Optional)"
        = f.text_field :description
      br			
      h2 Image
      p
        = f.label :image_file, "Upload an image:"
        = f.file_field :image_file
      p
        = f.label :image_url, "Or give image URL:"
        = f.text_field :image_url
      = f.submit "Create New Topic", class: "btn btn-info"