config/routes.rb
Rails.application.routes.draw do

  root to: 'topics#index'

  resources :topics do
  	resources :sub_topics do
      member do
        put :upvote
      end

      # collection do
      #   get :search
      # end

    	resources :comments
    end
  end

  resources :comments
  
  resources :sessions do

  end

  
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/signin', to: 'sessions#new', via: :get

end

app/models/sub_topic.rb
class SubTopic
	include Mongoid::Document
  include Mongoid::Timestamps

  field :title , type: String 
	field :created_by , type: String 
	field :descr , type: String
	field :score , type: Integer , default: 0
  field :active , type: Boolean , default: true
  field :url, type: String
  field :anonymous, type: Boolean , default: false
  
  embedded_in :topic
  embeds_many :comments
  embeds_many :votes

  validates :title, presence: true 

  def can_edit?(user)
    self.created_by == user.mail || user.admin?
  end

end

app/models/subtopic.rb
class Subtopic
	include MongoMapper::EmbeddedDocument
  many :comments

	key :title , String
	key :created_by , String 
	key :desc , String
	key :users , Array , :default => []
	key :score , Integer , :default => 0

	timestamps!
end

app/controllers/sub_topics_controller.rb
class SubTopicsController < ApplicationController
  helper_method :user_voted
  before_filter :signed_in_user, only: [:new, :create, :upvote, :destroy]
	
  def show
    begin 
      @topic = Topic.where(active: true).find_by(title: params[:topic_id])
      @sub_topic = @topic.sub_topics.where(active: true).find_by(_id: params[:id])
      @comments =  @sub_topic.comments.where(active: true)
    rescue
      redirect_to root_path
    end
	end

	def index
    begin
      @topic = Topic.where(active: true).find_by(title: params[:topic_id])
      @sub_topics = @topic.sub_topics.where(active: true).desc(:score)
    rescue
      redirect_to root_path
    end
	end

  def new
    @title = "Create New Kick"
    @topic = Topic.find_by(title: params[:topic_id])
    @subtopic = SubTopic.new
	end

	def create
    topic = Topic.find_by(title: params[:topic_id])
    if params[:sub_topic][:anonymous] == "1"
      topic.sub_topics << SubTopic.new(
        :created_by => "anonymous@90min.com",
        :descr => params[:sub_topic][:descr],
        :title => params[:sub_topic][:title],
        url: params[:sub_topic][:url],
        anonymous: params[:sub_topic][:anonymous]
        )
    else  
      topic.sub_topics << SubTopic.new(
        :created_by => cookies[:mail],
        :descr => params[:sub_topic][:descr],
        :title => params[:sub_topic][:title],
        url: params[:sub_topic][:url],
        anonymous: params[:sub_topic][:anonymous]
        )
    end  
    if topic.save
  		flash[:success] = "Subject created successfully"
  		redirect_to topic_sub_topics_path
    else
      flash[:error] = "Fields can't be blank"
      redirect_to :back  
    end  
	end

	def destroy
    @topic = Topic.where(active: true).find_by(title: params[:topic_id])
    @sub_topic = @topic.sub_topics.where(active: true).find_by(_id: params[:id])
    if @sub_topic.can_edit?(current_user)
      Topic.find_by(title: params[:topic_id]).sub_topics.find_by(id: params[:id]).set(active: false)
		  flash[:success] = "Subject destroyed." 
      redirect_to topic_sub_topics_path
    else
      flash[:error] = "You cant destroy this item."
      redirect_to :back       
    end  
	end

  def edit
    @title = "Update Your Kick"
    @topic = Topic.find_by(title: params[:topic_id])
    @subtopic = @topic.sub_topics.find_by(id: params[:id])
    if current_user.mail != @subtopic.created_by && !current_user.admin?
      flash[:notice] ="Sorry, you can't edit this Kick"
      redirect_to :back
    end
    render :new
  end

  def update
    @sub_topic = Topic.find_by(title: params[:topic_id]).sub_topics.find_by(id: params[:id])
    if @sub_topic.update(secure_params)
      flash[:notice] = "Your Item #{@sub_topic.title} has been updated" 
      redirect_to topic_sub_topic_path
    else
      flash[:error] = "Fields can't be blank"
      redirect_to :back      
    end  
  end

  def upvote
    topic = Topic.find_by(title: params[:topic_id])
    sub_topic = topic.sub_topics.find_by(id: params[:id])
    # byebug
    if sub_topic.votes.find_by(mail: cookies[:mail])
      if sub_topic.votes.find_by(mail: cookies[:mail]).voting == 1
        sub_topic.votes.find_by(mail: cookies[:mail]).destroy
        sub_topic.inc(score: -1)
      else
        sub_topic.votes.find_by(mail: cookies[:mail]).set(voting: 1)
        sub_topic.inc(score: 1)
      end
    else
      sub_topic.votes << Vote.new(
        mail: cookies[:mail],
        voting: 1,
        )
      sub_topic.inc(score: 1)
    end
    # bug on mongoid - creating empty instances 
    # https://github.com/mongoid/mongoid/issues/2735
    sub_topic.votes.where(mail: nil).destroy
    topic.save

    redirect_to topic_sub_topics_path
  end

  def user_voted(subtopic_id)
    begin
      topic = Topic.find_by(title: params[:topic_id])
      subtopic = topic.sub_topics.find_by(id: subtopic_id)
      subtopic.votes.where(mail: cookies[:mail]).last.voting == 1 
    rescue
      false
    end
  end


  private
    
    def secure_params
      params.require(:sub_topic).permit(:title, :descr, :url)
    end 

    def owner_of(topic_title, sub_topic_id)
      Topic.find_by(title: topic_title).sub_topics.find_by(id: sub_topic_id).created_by
    end

end

app/helpers/sub_topics_helper.rb
module SubTopicsHelper
  def show_name(subject)
    subject.created_by.to_s.split('@').first
  end
end

app/views/sub_topics/edit.html.slim
div.row
	div.span6.offset3

		h3 Edit your Item

		= form_for ([@sub_topic]) ,url: topic_sub_topic_path, method: :put do |f| 
			  = f.label :title 
			  br
				= f.text_field :title
				= f.label :description 
				br
				= f.text_area :descr 

				= f.submit "Update Your Item", class: "btn btn-info" 

app/views/sub_topics/index.html.slim
- provide(:title, 'SubTopics') 
div
  h1 = @topic.title 
  h2 = @topic.description
         
div.pull-right
  = "created by #{show_name(@topic)}"
br 
.reddit
  = link_to "Create New Item", "#{new_topic_sub_topic_path.to_s}", class: "btn btn-info"

  - @sub_topics.each do |sub_topic|
    div.well.well-small
      div.media
        span.score-section.pull-left
          - if current_user && current_user.mail == sub_topic.created_by
            i.fa.fa-thumbs-up.off
          - else
            = link_to upvote_topic_sub_topic_path(id: sub_topic.id) , method: :put
                - if user_voted(sub_topic.id)
                  i.fa.fa-thumbs-up.on
                - else
                  i.fa.fa-thumbs-up.off 
          span.score = sub_topic.score 
        span.pull-right  
          = sub_topic.comments.count.to_s + " " 
          i.icon-large.icon-comment 
        div.media-body
          h4.media-heading 
            = link_to "#{sub_topic.title} ", "#{topic_sub_topic_path(params[:topic_id], sub_topic.id)}"
            -if !sub_topic.url.blank?
              a.i.fa.fa-link href = sub_topic.url
          br
            = sub_topic.descr 
          span.pull-right
            br
              = "created #{distance_of_time_in_words_to_now(sub_topic.created_at).to_s}" + ' ago by ' "#{show_name(sub_topic)}"


     

app/views/sub_topics/new.html.slim
div.row
	div.span6.offset3

		h2 = @title

		= form_for ([@topic, @subtopic]) do |f| 
			  = f.label :title 
			  br
				= f.text_field :title
				= f.label :description, 'Description (Optional)'
				br
				= f.text_area :descr
				br 
				= f.label :url , "Link (Optional)"
				= f.text_field :url
				br
				.anonymous
					.an-checkbox= f.check_box :anonymous
					.an-label= f.label :anonymous, 'Post anonymously'
				

				= f.submit "Create New Reddit", class: "btn btn-info" 
				

app/views/sub_topics/show.html.erb
<h1><%= @sub_topic.title %></h1>
<div class="desc">
  <%= @sub_topic.desc %> 
  <p><small>Created By: <%= @sub_topic.created_by %></small></p>
</div>
<hr>

<% @sub_topic.comments.each do |comment|%>
<div class="well well-small">
<div class="media">
  <div class="media-body">
    <%= comment.body %> <br>
    <span class="pull-right">
    posted <%= distance_of_time_in_words_to_now(comment.created_at) %> ago by <%= comment.name %>
    </span>
  </div>
</div>
</div>
<%end%>
<%= render partial: 'comments/comment' %>

app/views/sub_topics/show.html.slim
span.pull-right 
  -if current_user && @sub_topic.can_edit?(current_user)
    .btn-group
      button.btn.btn-default = 'Admin Actions'
      button.btn.btn-default.dropdown-toggle data-toggle="dropdown"
        span.caret
        span.sr-only 

      ul.dropdown-menu role="menu"
        li 
          = link_to "Remove ", SubTopic.find_by(id: params[:id]), method: :delete, data: { confirm: "You sure?" }   
          = link_to "Edit", edit_topic_sub_topic_path(id: params[:id])
h4 =link_to "#{@topic.title} > ", topic_sub_topics_path(@topic.title)          
h1.sub-topic-title = "#{@sub_topic.title}"  

.desc = @sub_topic.descr 
span.pull-right = "Created by: #{@sub_topic.created_by.split('@').first}"



= render partial: 'comments/comment'