config/routes.rb
Rails.application.routes.draw do

  root to: 'topics#index'

  resources :topics do
  	resources :sub_topics do
      member do
        put :upvote
      end

      # collection do
      #   get :search
      # end

    	resources :comments
    end
  end

  resources :comments
  
  resources :sessions do

  end

  
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/signin', to: 'sessions#new', via: :get

end

app/views/layouts/_footer.html.slim
footer.footer
  nav
    ul
      li 
      	= link_to "About", '#' 
      li 
      	= link_to "Contact", '#' 
      li 
      	a href="http://www.ftbpro.com/" target="blank"   FTBpro
  = debug(params) if Rails.env.development? 

app/views/layouts/_header.html.slim
header.navbar.navbar-fixed-top
  div.navbar-inner
    div.container
      .ninety-min    
        = link_to "http://www.90min.com/", target: "blank" do  
          = image_tag("90min.png")
        end  
      = link_to "Kick-it", root_path, id: "logo" 
      nav
        ul.nav.pull-right
          li = link_to "Home", root_path 
          - if signed_in? 
            li
              = link_to "Welcome #{current_user.mail}" 
            li 
              = link_to "Sign out", signout_path, method: :delete 
          - else 
            li = link_to "Sign in", new_session_path 

app/views/layouts/application.html.slim
doctype html

html
	head
	  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true 
	  = javascript_include_tag 'application', 'data-turbolinks-track' => true 
	  = csrf_meta_tags 
	  title = full_title(yield(:title)) 
	body
		= render partial: "shared/flash_messages", flash: flash
		= render 'layouts/header' 
		.container
			= yield 
		= render 'layouts/footer' 